name: Update Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Roda a cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permissão para atualizar o branch
    
    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: Luizinz00
          svg_path: "assets/snake.svg"  # Caminho alternativo
          
      - name: Push to Repository
        uses: actions-js/push@master
        with:
          branch: output
          directory: assets
